# Generated by Django 4.2.9 on 2026-02-11 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Numéro WhatsApp')),
                ('institution', models.CharField(max_length=200, verbose_name='Institution / Organisation')),
                ('fonction', models.CharField(max_length=200, verbose_name='Fonction / Poste')),
                ('profil', models.CharField(choices=[('institution', 'Institution publique'), ('chercheur', 'Chercheur / Enseignant-chercheur'), ('etudiant', 'Étudiant (Master / Doctorat)'), ('entreprise', 'Entreprise / Startup tech'), ('ong', 'ONG / Société civile'), ('expert', 'Expert national ou international'), ('autre', 'Autre')], max_length=50, verbose_name='Profil')),
                ('atelier', models.CharField(choices=[('education', 'Éducation, enseignement supérieur, recherche & innovation'), ('sante', 'Santé & inclusion sociale'), ('justice', 'Justice, sécurité & défense'), ('rh_entreprise', "Ressources humaines, gestion d'entreprise & secteur informel"), ('agriculture', 'Agriculture & développement rural'), ('mines_env', 'Mines, environnement, climat & biosphère')], max_length=50, verbose_name='Atelier thématique choisi')),
                ('engagement', models.CharField(choices=[('participant', 'Participant'), ('contributeur', 'Contributeur actif'), ('observateur', 'Observateur'), ('intervenant', 'Intervenant / Expert')], max_length=50, verbose_name='Engagement souhaité')),
                ('format_preference', models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('hybride', 'Hybride (présentiel + distanciel)')], max_length=50, verbose_name='Format préféré')),
                ('disponibilite', models.CharField(choices=[('semaine', 'En semaine (journée)'), ('soir', 'En soirée'), ('weekend', 'Le week-end'), ('flexible', 'Flexible')], max_length=50, verbose_name='Disponibilité')),
                ('motivation', models.TextField(max_length=500, verbose_name='Motivation (500 caractères max)')),
                ('validation_engagement', models.BooleanField(default=False, verbose_name="Je m'engage à participer activement aux travaux de l'atelier choisi")),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
