# Generated by Django 4.2.9 on 2026-02-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='valide',
            field=models.BooleanField(default=False, verbose_name='Inscription validée'),
        ),
    ]
