# Generated by Django 4.2.9 on 2026-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_inscription_date_validation_inscription_valide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiffreCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(verbose_name='Nombre')),
                ('suffixe', models.CharField(blank=True, default='+', max_length=10, verbose_name='Suffixe (ex: +)')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Chiffre clé',
                'verbose_name_plural': 'Chiffres clés',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('specialite', models.CharField(max_length=200, verbose_name='Spécialité')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='experts/', verbose_name='Photo')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Expert',
                'verbose_name_plural': 'Experts',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/', verbose_name='Logo')),
                ('site_web', models.URLField(blank=True, default='', verbose_name='Site web')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='Guinée — Processus National', max_length=200, verbose_name='Hero badge')),
                ('hero_titre', models.CharField(default='DounIA — Données Numériques & Intelligence Artificielle', max_length=300, verbose_name='Hero titre')),
                ('hero_description', models.TextField(default="Un processus scientifique, collaboratif et indépendant visant à coconstruire une vision nationale autour de la gouvernance des données et de l'intelligence artificielle en Guinée.", verbose_name='Hero description')),
                ('hero_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&q=80', verbose_name='Hero image URL')),
                ('hero_btn1_texte', models.CharField(default='Télécharger le rapport', max_length=100, verbose_name='Hero bouton 1 texte')),
                ('hero_btn1_lien', models.CharField(default='#rapport', max_length=300, verbose_name='Hero bouton 1 lien')),
                ('hero_btn2_texte', models.CharField(default="S'inscrire aux ateliers", max_length=100, verbose_name='Hero bouton 2 texte')),
                ('hero_btn2_lien', models.CharField(default='#inscription', max_length=300, verbose_name='Hero bouton 2 lien')),
                ('about_titre', models.CharField(default="C'est quoi DounIA ?", max_length=200, verbose_name='About titre')),
                ('about_sous_titre', models.TextField(default="Comprendre les enjeux, structurer les réponses et bâtir une vision guinéenne autour de la donnée et de l'intelligence artificielle.", verbose_name='About sous-titre')),
                ('about_card1_icone', models.CharField(default='bi-globe-africa', max_length=50, verbose_name='About card 1 icône')),
                ('about_card1_titre', models.CharField(default='Un enjeu continental', max_length=200, verbose_name='About card 1 titre')),
                ('about_card1_texte', models.TextField(default="L'Afrique fait face à des défis majeurs en matière de souveraineté numérique, de gouvernance des données et d'adoption de l'IA. DounIA s'inscrit dans cette dynamique continentale pour positionner la Guinée comme acteur de sa transformation digitale.", verbose_name='About card 1 texte')),
                ('about_card2_icone', models.CharField(default='bi-diagram-3', max_length=50, verbose_name='About card 2 icône')),
                ('about_card2_titre', models.CharField(default='Un processus structurant', max_length=200, verbose_name='About card 2 titre')),
                ('about_card2_texte', models.TextField(default='DounIA est un cadre scientifique et indépendant qui réunit chercheurs, institutions, société civile et secteur privé pour coconstruire une approche nationale cohérente, inclusive et adaptée aux réalités guinéennes.', verbose_name='About card 2 texte')),
                ('about_card3_icone', models.CharField(default='bi-lightbulb', max_length=50, verbose_name='About card 3 icône')),
                ('about_card3_titre', models.CharField(default='Des ambitions concrètes', max_length=200, verbose_name='About card 3 titre')),
                ('about_card3_texte', models.TextField(default="De la réflexion à l'action : DounIA vise à produire des recommandations opérationnelles, des feuilles de route sectorielles et des cadres de gouvernance adaptés au contexte guinéen et ouest-africain.", verbose_name='About card 3 texte')),
                ('dounia1_titre', models.CharField(default='DounIA 1 — Contexte & Enseignements', max_length=200, verbose_name='DounIA 1 titre')),
                ('dounia1_sous_titre', models.TextField(default="La première édition a permis d'établir un diagnostic approfondi et de poser les bases d'un dialogue national structuré autour de l'IA et des données.", verbose_name='DounIA 1 sous-titre')),
                ('dounia1_defis', models.TextField(default="Absence de cadre réglementaire spécifique à l'IA et à la protection des données personnelles\nFracture numérique persistante entre zones urbaines et rurales\nFaible capacité en recherche et innovation dans le domaine de l'IA\nManque de données structurées et ouvertes pour l'entraînement de modèles locaux", help_text='Un défi par ligne', verbose_name='DounIA 1 défis (un par ligne)')),
                ('dounia1_opportunites', models.TextField(default="Potentiel élevé dans l'agriculture, la santé et l'éducation grâce à l'IA\nJeunesse dynamique et connectée, moteur d'innovation\nRessources naturelles dont la gestion peut être optimisée par les technologies numériques\nMobilisation croissante de la diaspora scientifique et technique", help_text='Une opportunité par ligne', verbose_name='DounIA 1 opportunités (une par ligne)')),
                ('rapport_titre', models.CharField(default='Rapport DounIA 1', max_length=200, verbose_name='Rapport titre')),
                ('rapport_sous_titre', models.TextField(default="Consultez le rapport complet de la première édition de DounIA : diagnostic, recommandations et feuille de route pour la gouvernance de l'IA en Guinée.", verbose_name='Rapport sous-titre')),
                ('rapport_description', models.TextField(default="Ce rapport présente les résultats de la première phase du processus DounIA, incluant l'état des lieux de l'écosystème numérique guinéen, les défis identifiés, les opportunités par secteur et les recommandations stratégiques pour une gouvernance responsable de l'IA.", verbose_name='Rapport description')),
                ('rapport_points', models.TextField(default="Diagnostic de l'écosystème numérique\nAnalyse sectorielle approfondie\nRecommandations stratégiques\nFeuille de route opérationnelle", verbose_name='Rapport points clés (un par ligne)')),
                ('rapport_lien', models.URLField(blank=True, default='', verbose_name='Lien de téléchargement du rapport')),
                ('podcast_titre', models.CharField(default='Podcast DounIA', max_length=200, verbose_name='Podcast titre')),
                ('podcast_description', models.TextField(default="Écoutez les échanges, interviews et analyses des experts ayant participé au processus DounIA. Des discussions autour de la gouvernance de l'IA, de la souveraineté numérique et des enjeux spécifiques à la Guinée et au continent africain.", verbose_name='Podcast description')),
                ('podcast_lien', models.URLField(blank=True, default='', verbose_name='Lien du podcast')),
                ('dounia2_badge', models.CharField(default='Prochaine étape', max_length=200, verbose_name='DounIA 2 badge')),
                ('dounia2_titre', models.CharField(default='DounIA 2 — La suite du processus', max_length=200, verbose_name='DounIA 2 titre')),
                ('dounia2_description', models.TextField(default="Après la phase de diagnostic et de consultation, DounIA 2 marque le passage de la réflexion vers l'action. Des travaux sectoriels approfondis seront menés à travers des ateliers thématiques prévus pour octobre 2026, réunissant experts, praticiens et décideurs.", verbose_name='DounIA 2 description')),
                ('dounia2_phase1', models.TextField(default='Phase 1 — Diagnostic (terminée)|DounIA 1 : consultation nationale, 600+ participants, rapport publié.', verbose_name='Phase 1 (titre|description)')),
                ('dounia2_phase2', models.TextField(default='Phase 2 — Inscriptions & préparation|Ouverture des inscriptions aux ateliers thématiques, constitution des groupes de travail.', verbose_name='Phase 2 (titre|description)')),
                ('dounia2_phase3', models.TextField(default='Phase 3 — Ateliers sectoriels (Oct. 2026)|6 ateliers thématiques avec production de recommandations et feuilles de route.', verbose_name='Phase 3 (titre|description)')),
                ('dounia2_phase4', models.TextField(default="Phase 4 — Synthèse & publication|Rapport DounIA 2, plan d'action national et présentation aux décideurs.", verbose_name='Phase 4 (titre|description)')),
                ('inscription_titre', models.CharField(default='Inscription aux Ateliers DounIA 2', max_length=200, verbose_name='Section inscription titre')),
                ('inscription_sous_titre', models.TextField(default="Remplissez le formulaire ci-dessous pour vous inscrire à l'atelier thématique de votre choix. Tous les champs sont obligatoires.", verbose_name='Section inscription sous-titre')),
                ('footer_description', models.TextField(default="DounIA est un processus scientifique national visant à coconstruire une vision guinéenne autour de l'IA et de la gouvernance des données.", verbose_name='Footer description')),
                ('footer_email', models.EmailField(default='contact@dounia.gn', max_length=254, verbose_name='Email de contact')),
                ('footer_lieu', models.CharField(default='Conakry, Guinée', max_length=200, verbose_name='Lieu')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
