# Generated by Django 4.2.9 on 2026-02-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_chiffrecle_expert_partenaire_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Hero image (upload)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&q=80', verbose_name='Hero image URL (fallback)'),
        ),
    ]
