# Generated by Django 4.2.9 on 2026-02-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0004_siteconfiguration_hero_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'image")),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_carousel/', verbose_name='Image (upload)')),
                ('image_url', models.URLField(blank=True, verbose_name="URL de l'image (alternative)")),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Image du carrousel Hero',
                'verbose_name_plural': 'Images du carrousel Hero',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
