# Generated by Django 6.0 on 2026-02-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0005_herocarouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_images/', verbose_name='Image uploadée')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name="URL de l'image")),
                ('position', models.CharField(choices=[('gauche', 'Gauche (carousel)'), ('arriere', 'Arrière-plan (défilant)')], default='gauche', max_length=20, verbose_name='Position')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Image Hero',
                'verbose_name_plural': 'Images Hero',
                'ordering': ['position', 'ordre', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='StatsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stats_images/', verbose_name='Image uploadée')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name="URL de l'image")),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Image Statistiques',
                'verbose_name_plural': 'Images Statistiques',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
