# Generated by Django 6.0 on 2026-02-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0006_heroimage_statsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='motivation',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Motivation (500 caractères max)'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='profil',
            field=models.CharField(choices=[('institution', 'Institution publique'), ('chercheur', 'Chercheur / Enseignant-chercheur'), ('etudiant', 'Étudiant'), ('entreprise', 'Entreprise / Startup tech'), ('ong', 'ONG / Société civile'), ('expert', 'Expert national ou international'), ('autre', 'Autre')], max_length=50, verbose_name='Profil'),
        ),
    ]
