# Generated by Django 6.0 on 2026-02-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0007_alter_inscription_motivation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='profil_autre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Profil (autre, précisez)'),
        ),
    ]
