# Generated by Django 6.0 on 2026-02-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0008_inscription_profil_autre'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='categorie',
            field=models.CharField(choices=[('institutionnel', 'Partenaire institutionnel'), ('technique', 'Partenaire technique')], default='institutionnel', max_length=20, verbose_name='Catégorie'),
        ),
    ]
