# Generated by Django 6.0 on 2026-02-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0009_partenaire_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='rapport_fichier',
            field=models.FileField(blank=True, null=True, upload_to='rapports/', verbose_name='Fichier PDF du rapport'),
        ),
    ]
