# Generated by Django 6.0 on 2026-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0010_siteconfiguration_rapport_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='porteur1_description',
            field=models.CharField(default="Cité des Sciences et de l'Innovation de Guinée", max_length=300, verbose_name='Porteur 1 — Description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='porteur1_logo',
            field=models.ImageField(blank=True, null=True, upload_to='porteurs/', verbose_name='Porteur 1 — Logo'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='porteur1_nom',
            field=models.CharField(default='CSIG', max_length=200, verbose_name='Porteur 1 — Nom'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='porteur2_description',
            field=models.CharField(default='Académie des Sciences de Guinée', max_length=300, verbose_name='Porteur 2 — Description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='porteur2_logo',
            field=models.ImageField(blank=True, null=True, upload_to='porteurs/', verbose_name='Porteur 2 — Logo'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='porteur2_nom',
            field=models.CharField(default='ASG', max_length=200, verbose_name='Porteur 2 — Nom'),
        ),
    ]
