# Generated by Django 6.0 on 2026-02-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0011_siteconfiguration_porteur1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='video_fichier',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Fichier vidéo (MP4)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='video_lien',   
            field=models.URLField(blank=True, default='', verbose_name='Lien vidéo (YouTube, Vimeo...)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='video_sous_titre',
            field=models.TextField(default='Découvrez DounIA en images', verbose_name='Sous-titre de la section vidéo'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='video_titre',
            field=models.CharField(default='Vidéo de présentation', max_length=200, verbose_name='Titre de la section vidéo'),
        ),
    ]
