# Generated by Django 6.0 on 2026-02-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0012_siteconfiguration_video_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='rapport_image',
            field=models.ImageField(blank=True, null=True, upload_to='rapports/', verbose_name='Image de couverture du rapport'),
        ),
    ]
