# Generated by Django 6.0 on 2026-02-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0013_siteconfiguration_rapport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='podcast_fichier',
            field=models.FileField(blank=True, null=True, upload_to='podcasts/', verbose_name='Fichier audio du podcast (MP3/WAV)'),
        ),
    ]
