# Generated by Django 4.2.28 on 2026-02-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0017_atelier_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
