# Generated by Django 4.2.28 on 2026-02-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0018_add_atelier_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_hero', models.CharField(default='Restitution DounIA', max_length=200)),
                ('description_hero', models.TextField(default="Découvrez les résultats, recommandations et conclusions des ateliers de concertation sur la gouvernance des données et l'intelligence artificielle en Guinée.")),
                ('mission_titre', models.CharField(default='Mission Principale', max_length=200)),
                ('mission_description', models.TextField(default="Présenter les synthèses des ateliers thématiques et les recommandations stratégiques pour une gouvernance inclusive des données et de l'IA en Guinée.")),
                ('mission_points', models.JSONField(blank=True, default=list, help_text='Liste des points de la mission')),
                ('public_titre', models.CharField(default='Public Ciblé', max_length=200)),
                ('public_description', models.TextField(default="Cette restitution s'adresse à l'ensemble des acteurs impliqués dans la transformation numérique du pays.")),
                ('public_points', models.JSONField(blank=True, default=list, help_text='Liste du public ciblé')),
                ('participants_nombre', models.CharField(default='150+', max_length=50)),
                ('participants_label', models.CharField(default='Participants', max_length=100)),
                ('ateliers_nombre', models.CharField(default='8', max_length=50)),
                ('ateliers_label', models.CharField(default='Ateliers thématiques', max_length=100)),
                ('recommandations_nombre', models.CharField(default='50+', max_length=50)),
                ('recommandations_label', models.CharField(default='Recommandations', max_length=100)),
                ('duree_nombre', models.CharField(default='3', max_length=50)),
                ('duree_label', models.CharField(default='Mois de concertation', max_length=100)),
                ('rapport_synthese_titre', models.CharField(default='Rapport Synthétique', max_length=200)),
                ('rapport_synthese_description', models.TextField(default='Rapport complet présentant les conclusions et recommandations des ateliers DounIA.')),
                ('rapport_synthese_fichier', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('rapport_detail_titre', models.CharField(default='Recommandations Détaillées', max_length=200)),
                ('rapport_detail_description', models.TextField(default="Document détaillé avec l'ensemble des recommandations par atelier thématique.")),
                ('rapport_detail_fichier', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('chronologie', models.JSONField(blank=True, default=list, help_text='Liste des événements de la chronologie')),
                ('cta_titre', models.CharField(default='Rejoignez la Démarche DounIA', max_length=200)),
                ('cta_description', models.TextField(default="Participez à la construction de l'avenir numérique de la Guinée")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restitution',
                'verbose_name_plural': 'Restitutions',
            },
        ),
    ]
