# Generated by Django 4.2.28 on 2026-02-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0019_restitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='DouniaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_slug', models.CharField(choices=[('dounia1', 'DounIA 1'), ('dounia2', 'DounIA 2')], max_length=20, unique=True)),
                ('titre_hero', models.CharField(max_length=200)),
                ('description_hero', models.TextField()),
                ('bouton_principal_texte', models.CharField(default="S'inscrire", max_length=100)),
                ('bouton_principal_lien', models.CharField(default='#inscription', max_length=200)),
                ('bouton_secondaire_texte', models.CharField(default='En savoir plus', max_length=100)),
                ('bouton_secondaire_lien', models.CharField(default='#', max_length=200)),
                ('objectifs_titre', models.CharField(default='Objectifs', max_length=200)),
                ('objectifs_description', models.TextField()),
                ('objectifs_points', models.JSONField(blank=True, default=list, help_text='Liste des objectifs')),
                ('chiffres_titre', models.CharField(default='Chiffres clés', max_length=200)),
                ('chiffres', models.JSONField(blank=True, default=list, help_text='Liste des chiffres avec nombre et label')),
                ('programme_titre', models.CharField(default='Programme', max_length=200)),
                ('programme_description', models.TextField()),
                ('programme_sessions', models.JSONField(blank=True, default=list, help_text='Liste des sessions avec heure, titre et description')),
                ('partenaires_titre', models.CharField(default='Partenaires', max_length=200)),
                ('partenaires_description', models.TextField(default='')),
                ('inscription_titre', models.CharField(default='Inscription', max_length=200)),
                ('inscription_description', models.TextField()),
                ('inscription_date_limite', models.DateField(blank=True, null=True)),
                ('inscription_lieu', models.CharField(blank=True, max_length=200)),
                ('contact_titre', models.CharField(default='Contact', max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_telephone', models.CharField(blank=True, max_length=20)),
                ('contact_adresse', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement DounIA',
                'verbose_name_plural': 'Événements DounIA',
            },
        ),
    ]
