# Generated by Django 4.2.28 on 2026-02-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0020_douniaevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestitutionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'image")),
                ('image', models.ImageField(upload_to='restitution_images/', verbose_name='Image')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name="URL de l'image (fallback)")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Image de restitution',
                'verbose_name_plural': 'Images de restitution',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
