# Generated by Django 4.2.28 on 2026-02-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0021_add_evenement_and_restitution_images'),
    ]

    operations = [
    ]
