# Generated by Django 4.2.28 on 2026-02-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0026_ensure_image_position_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenementimage',
            options={'ordering': ['ordre', 'date_ajout'], 'verbose_name': "Image d'événement", 'verbose_name_plural': "Images d'événement"},
        ),
        migrations.AddField(
            model_name='douniaevent',
            name='chiffres_image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/chiffres/', verbose_name='Image Statistiques (upload)'),
        ),
        migrations.AddField(
            model_name='douniaevent',
            name='chiffres_image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Image Statistiques URL (fallback)'),
        ),
        migrations.AddField(
            model_name='douniaevent',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/hero/', verbose_name='Image Hero (upload)'),
        ),
        migrations.AddField(
            model_name='douniaevent',
            name='hero_image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Image Hero URL (fallback)'),
        ),
        migrations.AlterField(
            model_name='evenementimage',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inscriptions.douniaevent', verbose_name='Événement'),
        ),
        migrations.AlterField(
            model_name='evenementimage',
            name='titre',
            field=models.CharField(max_length=200, verbose_name="Titre de l'image"),
        ),
        migrations.AlterField(
            model_name='restitutionimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restitution_images/', verbose_name='Image'),
        ),
    ]
