# Generated by Django 4.2.28 on 2026-02-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0027_alter_evenementimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restitution',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='restitution/hero/', verbose_name='Image Hero (upload)'),
        ),
        migrations.AddField(
            model_name='restitution',
            name='hero_image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Image Hero URL (fallback)'),
        ),
    ]
