# Generated by Django 4.2.28 on 2026-03-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0032_restitution_seed_ceremony_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='contexte',
            field=models.TextField(blank=True, default='', help_text="Texte décrivant le contexte de l'atelier", verbose_name='Contexte'),
        ),
        migrations.AddField(
            model_name='atelier',
            name='intervenants',
            field=models.TextField(blank=True, default='', help_text='Liste des intervenants prévus', verbose_name='Intervenants'),
        ),
        migrations.AddField(
            model_name='atelier',
            name='lien_inscription',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name="Lien d'inscription"),
        ),
        migrations.AddField(
            model_name='atelier',
            name='objectif',
            field=models.TextField(blank=True, default='', help_text="Objectif principal de l'atelier", verbose_name='Objectif'),
        ),
        migrations.AddField(
            model_name='atelier',
            name='questions_cles',
            field=models.TextField(blank=True, default='', help_text="Questions clés à traiter lors de l'atelier", verbose_name='Questions clés'),
        ),
    ]
