# Generated by Django 4.2.28 on 2026-03-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0034_seed_atelier_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='restitution',
            name='agenda_date',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='restitution',
            name='agenda_duree',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='restitution',
            name='agenda_invites',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='restitution',
            name='agenda_sessions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restitution',
            name='agenda_titre',
            field=models.CharField(default='Programme (Agenda)', max_length=200),
        ),
    ]
