# Generated by Django 4.2.28 on 2026-03-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0036_seed_restitution_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='restitution',
            name='agenda_empty_message',
            field=models.CharField(default='Le programme sera bientôt publié.', max_length=200),
        ),
        migrations.AddField(
            model_name='restitution',
            name='agenda_label_date',
            field=models.CharField(default='Date', max_length=100),
        ),
        migrations.AddField(
            model_name='restitution',
            name='agenda_label_duree',
            field=models.CharField(default='Durée', max_length=100),
        ),
        migrations.AddField(
            model_name='restitution',
            name='agenda_label_invites',
            field=models.CharField(default="Nombre total d'invités", max_length=200),
        ),
        migrations.AddField(
            model_name='restitution',
            name='resultats_intro',
            field=models.CharField(default='À l’issue de la cérémonie :', max_length=200),
        ),
        migrations.AddField(
            model_name='restitution',
            name='section_titre',
            field=models.CharField(default='Restitution DounIA 1', max_length=200),
        ),
    ]
