# Generated by Django 4.2.28 on 2026-03-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0037_restitution_agenda_empty_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restitution',
            name='countdown_date',
            field=models.DateTimeField(blank=True, help_text='Date cible pour le compte à rebours (ex: 2026-04-01 09:00)', null=True, verbose_name='Date du countdown'),
        ),
        migrations.AddField(
            model_name='restitution',
            name='galerie_titre',
            field=models.CharField(default='Galerie DounIA 1', max_length=200, verbose_name='Titre Galerie'),
        ),
        migrations.AddField(
            model_name='restitution',
            name='hero_badge_text',
            field=models.CharField(default='Restitution officielle', max_length=200, verbose_name='Badge Hero'),
        ),
        migrations.AddField(
            model_name='restitution',
            name='hero_btn1_lien',
            field=models.CharField(default='#contexte', max_length=200, verbose_name='Bouton 1 lien'),
        ),
        migrations.AddField(
            model_name='restitution',
            name='hero_btn1_texte',
            field=models.CharField(default='Voir le contenu', max_length=100, verbose_name='Bouton 1 texte'),
        ),
        migrations.AddField(
            model_name='restitution',
            name='hero_btn2_lien',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Bouton 2 lien (vide = landing#livrable)'),
        ),
        migrations.AddField(
            model_name='restitution',
            name='hero_btn2_texte',
            field=models.CharField(default='Rapport', max_length=100, verbose_name='Bouton 2 texte'),
        ),
    ]
