# Generated by Django 4.2.28 on 2026-03-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0039_siteconfiguration_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restitution',
            name='galerie_titre',
            field=models.CharField(default='Galerie DounIA¹', max_length=200, verbose_name='Titre Galerie'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='section_titre',
            field=models.CharField(default='Restitution DounIA¹', max_length=200),
        ),
    ]
