# Generated by Django 4.2.28 on 2026-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0040_alter_restitution_galerie_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restitution',
            name='tdr_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF des Termes de Référence', null=True, upload_to='restitution/tdr/', verbose_name='TDR PDF'),
        ),
    ]
