# Generated by Django 4.2.28 on 2026-03-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0041_restitution_tdr_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='douniaevent',
            name='date_lancement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de lancement (compte à rebours)'),
        ),
    ]
