# Generated by Django 4.2.28 on 2026-03-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0042_douniaevent_date_lancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='date_lancement_site',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de lancement du site (compte à rebours hero)'),
        ),
    ]
