# Generated by Django 4.2.28 on 2026-03-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0043_siteconfiguration_date_lancement_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='date_lancement_site',
        ),
    ]
