# Generated by Django 4.2.28 on 2026-03-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0045_siteconfiguration_date_lancement_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('event_slug', models.CharField(choices=[('dounia1', 'DounIA 1'), ('dounia2', 'DounIA 2')], default='dounia1', max_length=20, verbose_name='Événement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date_creation'],
            },
        ),
    ]
