# Generated by Django 4.2.28 on 2026-03-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0046_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='podcast_video',
            field=models.FileField(blank=True, null=True, upload_to='podcasts/', verbose_name='Vidéo du podcast (MP4)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='podcast_video_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL vidéo du podcast (YouTube, etc.)'),
        ),
    ]
