# Generated by Django 4.2.28 on 2026-03-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0047_siteconfiguration_podcast_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='galerie_video_1',
            field=models.FileField(blank=True, null=True, upload_to='galerie_videos/', verbose_name='Galerie vidéo 1'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='galerie_video_2',
            field=models.FileField(blank=True, null=True, upload_to='galerie_videos/', verbose_name='Galerie vidéo 2'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='galerie_video_3',
            field=models.FileField(blank=True, null=True, upload_to='galerie_videos/', verbose_name='Galerie vidéo 3'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='galerie_video_4',
            field=models.FileField(blank=True, null=True, upload_to='galerie_videos/', verbose_name='Galerie vidéo 4'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='galerie_video_5',
            field=models.FileField(blank=True, null=True, upload_to='galerie_videos/', verbose_name='Galerie vidéo 5'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='galerie_videos_titre',
            field=models.CharField(default='Nos Vidéos', max_length=200, verbose_name='Galerie vidéos — Titre'),
        ),
    ]
