# Generated by Django 4.2.28 on 2026-03-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0048_siteconfiguration_galerie_video_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='galerie_videos_titre',
            field=models.CharField(default='Podcast', max_length=200, verbose_name='Galerie vidéos — Titre'),
        ),
    ]
