# Generated by Django 4.2.28 on 2026-03-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0049_alter_siteconfiguration_galerie_videos_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='douniaevent',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='evenements/hero_videos/', verbose_name='Vidéo Hero (upload)'),
        ),
    ]
