# Generated by Django 4.2.28 on 2026-03-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0049_alter_siteconfiguration_galerie_videos_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='categorie',
            field=models.CharField(choices=[('institutionnel', 'Partenaire institutionnel'), ('technique', 'Co-organisateur')], default='institutionnel', max_length=20, verbose_name='Catégorie'),
        ),
    ]
