# Generated by Django 4.2.28 on 2026-03-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0051_merge_20260328_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='douniaevent',
            name='hero_video_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Vidéo Hero URL'),
        ),
    ]
