# Generated by Django 4.2.28 on 2026-03-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0052_douniaevent_hero_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='splash_audio_url',
            field=models.URLField(blank=True, default='https://assets.mixkit.co/sfx/preview/mixkit-forest-ambience-1209.mp3', max_length=500, verbose_name='Splash — URL audio jungle'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='splash_duree',
            field=models.PositiveIntegerField(default=20, verbose_name='Splash — Durée du décompte (secondes)'),
        ),
    ]
