# Generated by Django 4.2.28 on 2026-03-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0053_add_splash_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='splash_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='splash_audio/', verbose_name='Splash — Fichier audio (MP3/OGG)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='splash_audio_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Splash — URL audio (si pas de fichier uploadé)'),
        ),
    ]
