# Generated by Django 4.2.28 on 2026-03-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0054_add_splash_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='podcast_youtube_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Chaîne YouTube CSIG (lien vers la chaîne ou playlist)'),
        ),
    ]
