# Generated by Django 4.2.28 on 2026-03-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0055_add_podcast_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone'),
        ),
    ]
