# Generated by Django 4.2.28 on 2026-03-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0057_add_align_fields_to_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='text_alignments',
            field=models.JSONField(blank=True, default=dict, verbose_name='Alignements de texte par champ'),
        ),
    ]
