# Generated by Django 4.2.28 on 2026-03-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0058_add_text_alignments_json_to_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='restitution',
            name='rapport_detail_lien',
            field=models.URLField(blank=True, default='', verbose_name='Lien externe rapport détaillé (Google Drive, Dropbox…)'),
        ),
        migrations.AddField(
            model_name='restitution',
            name='rapport_synthese_lien',
            field=models.URLField(blank=True, default='', verbose_name='Lien externe rapport synthèse (Google Drive, Dropbox…)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_align',
            field=models.CharField(choices=[('center', 'Centré'), ('left', 'Gauche'), ('right', 'Droite'), ('justify', 'Justifié')], default='center', max_length=10, verbose_name='À propos — Alignement du texte'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='ateliers_align',
            field=models.CharField(choices=[('center', 'Centré'), ('left', 'Gauche'), ('right', 'Droite'), ('justify', 'Justifié')], default='center', max_length=10, verbose_name='Ateliers — Alignement du texte'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='calendrier_align',
            field=models.CharField(choices=[('center', 'Centré'), ('left', 'Gauche'), ('right', 'Droite'), ('justify', 'Justifié')], default='center', max_length=10, verbose_name='Calendrier — Alignement du texte'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='dounia1_align',
            field=models.CharField(choices=[('center', 'Centré'), ('left', 'Gauche'), ('right', 'Droite'), ('justify', 'Justifié')], default='center', max_length=10, verbose_name='DounIA 1 — Alignement du texte'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='dounia2_align',
            field=models.CharField(choices=[('center', 'Centré'), ('left', 'Gauche'), ('right', 'Droite'), ('justify', 'Justifié')], default='center', max_length=10, verbose_name='DounIA 2 — Alignement du texte'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='evenements_align',
            field=models.CharField(choices=[('center', 'Centré'), ('left', 'Gauche'), ('right', 'Droite'), ('justify', 'Justifié')], default='center', max_length=10, verbose_name='Événements — Alignement du texte'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='experts_align',
            field=models.CharField(choices=[('center', 'Centré'), ('left', 'Gauche'), ('right', 'Droite'), ('justify', 'Justifié')], default='center', max_length=10, verbose_name='Experts — Alignement du texte'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='inscription_align',
            field=models.CharField(choices=[('center', 'Centré'), ('left', 'Gauche'), ('right', 'Droite'), ('justify', 'Justifié')], default='center', max_length=10, verbose_name='Inscription — Alignement du texte'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='rapport_align',
            field=models.CharField(choices=[('center', 'Centré'), ('left', 'Gauche'), ('right', 'Droite'), ('justify', 'Justifié')], default='center', max_length=10, verbose_name='Rapport — Alignement du texte'),
        ),
    ]
