# Generated by Django 4.2.28 on 2026-03-31 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0059_add_rapport_lien_to_restitution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restitution',
            name='rapport_detail_lien',
        ),
        migrations.RemoveField(
            model_name='restitution',
            name='rapport_synthese_lien',
        ),
    ]
