# Generated by Django 4.2.28 on 2026-03-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0060_remove_rapport_lien_from_restitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='countdown_actif',
            field=models.BooleanField(default=True, verbose_name='Compte à rebours — Activer'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='splash_actif',
            field=models.BooleanField(default=True, verbose_name="Splash — Activer l'écran de chargement"),
        ),
    ]
