# Generated by Django 4.2.28 on 2026-04-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0061_add_splash_countdown_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_about_hero_badge',
            field=models.CharField(blank=True, default='Découvrir DounIA', max_length=200, verbose_name='Page À propos — Badge hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_about_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages_hero/', verbose_name='Page À propos — Image hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_ateliers_hero_badge',
            field=models.CharField(blank=True, default='Thématiques', max_length=200, verbose_name='Page Ateliers — Badge hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_ateliers_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages_hero/', verbose_name='Page Ateliers — Image hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_evenements_hero_badge',
            field=models.CharField(blank=True, default='Nos événements', max_length=200, verbose_name='Page Événements — Badge hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_evenements_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages_hero/', verbose_name='Page Événements — Image hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_livrable_hero_badge',
            field=models.CharField(blank=True, default='Rapport', max_length=200, verbose_name='Page Livrable — Badge hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_livrable_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages_hero/', verbose_name='Page Livrable — Image hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_podcast_hero_badge',
            field=models.CharField(blank=True, default='Podcast', max_length=200, verbose_name='Page Podcast — Badge hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_podcast_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages_hero/', verbose_name='Page Podcast — Image hero'),
        ),
    ]
