# Generated by Django 4.2.28 on 2026-04-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0062_siteconfiguration_page_about_hero_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_slide_desc_bold',
            field=models.BooleanField(default=False, verbose_name='Slides hero — Description en gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_slide_desc_italic',
            field=models.BooleanField(default=False, verbose_name='Slides hero — Description en italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_slide_desc_size',
            field=models.CharField(blank=True, default='1.05rem', max_length=20, verbose_name='Slides hero — Taille de la description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_slide_font',
            field=models.CharField(blank=True, choices=[('inherit', 'Par défaut'), ("'Poppins', sans-serif", 'Poppins'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Playfair Display', serif", 'Playfair Display'), ("'Roboto', sans-serif", 'Roboto'), ("'Raleway', sans-serif", 'Raleway'), ("'Oswald', sans-serif", 'Oswald'), ("'Lora', serif", 'Lora')], default='inherit', max_length=100, verbose_name='Slides hero — Police'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_slide_titre_bold',
            field=models.BooleanField(default=True, verbose_name='Slides hero — Titre en gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_slide_titre_italic',
            field=models.BooleanField(default=False, verbose_name='Slides hero — Titre en italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_slide_titre_size',
            field=models.CharField(blank=True, default='2.4rem', max_length=20, verbose_name='Slides hero — Taille du titre'),
        ),
    ]
