# Generated by Django 4.2.28 on 2026-04-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0063_siteconfiguration_hero_slide_desc_bold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_about_desc_bold',
            field=models.BooleanField(default=False, verbose_name='Page À propos — Description gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_about_desc_italic',
            field=models.BooleanField(default=False, verbose_name='Page À propos — Description italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_about_desc_size',
            field=models.CharField(blank=True, default='1.05rem', max_length=20, verbose_name='Page À propos — Taille description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_about_font',
            field=models.CharField(blank=True, choices=[('inherit', 'Par défaut'), ("'Poppins', sans-serif", 'Poppins'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Playfair Display', serif", 'Playfair Display'), ("'Roboto', sans-serif", 'Roboto'), ("'Raleway', sans-serif", 'Raleway'), ("'Oswald', sans-serif", 'Oswald'), ("'Lora', serif", 'Lora')], default='inherit', max_length=100, verbose_name='Page À propos — Police'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_about_titre_bold',
            field=models.BooleanField(default=True, verbose_name='Page À propos — Titre gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_about_titre_italic',
            field=models.BooleanField(default=False, verbose_name='Page À propos — Titre italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_about_titre_size',
            field=models.CharField(blank=True, default='2.4rem', max_length=20, verbose_name='Page À propos — Taille titre'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_ateliers_desc_bold',
            field=models.BooleanField(default=False, verbose_name='Page Ateliers — Description gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_ateliers_desc_italic',
            field=models.BooleanField(default=False, verbose_name='Page Ateliers — Description italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_ateliers_desc_size',
            field=models.CharField(blank=True, default='1.05rem', max_length=20, verbose_name='Page Ateliers — Taille description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_ateliers_font',
            field=models.CharField(blank=True, choices=[('inherit', 'Par défaut'), ("'Poppins', sans-serif", 'Poppins'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Playfair Display', serif", 'Playfair Display'), ("'Roboto', sans-serif", 'Roboto'), ("'Raleway', sans-serif", 'Raleway'), ("'Oswald', sans-serif", 'Oswald'), ("'Lora', serif", 'Lora')], default='inherit', max_length=100, verbose_name='Page Ateliers — Police'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_ateliers_titre_bold',
            field=models.BooleanField(default=True, verbose_name='Page Ateliers — Titre gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_ateliers_titre_italic',
            field=models.BooleanField(default=False, verbose_name='Page Ateliers — Titre italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_ateliers_titre_size',
            field=models.CharField(blank=True, default='2.4rem', max_length=20, verbose_name='Page Ateliers — Taille titre'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_evenements_desc_bold',
            field=models.BooleanField(default=False, verbose_name='Page Événements — Description gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_evenements_desc_italic',
            field=models.BooleanField(default=False, verbose_name='Page Événements — Description italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_evenements_desc_size',
            field=models.CharField(blank=True, default='1.05rem', max_length=20, verbose_name='Page Événements — Taille description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_evenements_font',
            field=models.CharField(blank=True, choices=[('inherit', 'Par défaut'), ("'Poppins', sans-serif", 'Poppins'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Playfair Display', serif", 'Playfair Display'), ("'Roboto', sans-serif", 'Roboto'), ("'Raleway', sans-serif", 'Raleway'), ("'Oswald', sans-serif", 'Oswald'), ("'Lora', serif", 'Lora')], default='inherit', max_length=100, verbose_name='Page Événements — Police'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_evenements_titre_bold',
            field=models.BooleanField(default=True, verbose_name='Page Événements — Titre gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_evenements_titre_italic',
            field=models.BooleanField(default=False, verbose_name='Page Événements — Titre italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_evenements_titre_size',
            field=models.CharField(blank=True, default='2.4rem', max_length=20, verbose_name='Page Événements — Taille titre'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_livrable_desc_bold',
            field=models.BooleanField(default=False, verbose_name='Page Livrable — Description gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_livrable_desc_italic',
            field=models.BooleanField(default=False, verbose_name='Page Livrable — Description italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_livrable_desc_size',
            field=models.CharField(blank=True, default='1.05rem', max_length=20, verbose_name='Page Livrable — Taille description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_livrable_font',
            field=models.CharField(blank=True, choices=[('inherit', 'Par défaut'), ("'Poppins', sans-serif", 'Poppins'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Playfair Display', serif", 'Playfair Display'), ("'Roboto', sans-serif", 'Roboto'), ("'Raleway', sans-serif", 'Raleway'), ("'Oswald', sans-serif", 'Oswald'), ("'Lora', serif", 'Lora')], default='inherit', max_length=100, verbose_name='Page Livrable — Police'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_livrable_titre_bold',
            field=models.BooleanField(default=True, verbose_name='Page Livrable — Titre gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_livrable_titre_italic',
            field=models.BooleanField(default=False, verbose_name='Page Livrable — Titre italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_livrable_titre_size',
            field=models.CharField(blank=True, default='2.4rem', max_length=20, verbose_name='Page Livrable — Taille titre'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_podcast_desc_bold',
            field=models.BooleanField(default=False, verbose_name='Page Podcast — Description gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_podcast_desc_italic',
            field=models.BooleanField(default=False, verbose_name='Page Podcast — Description italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_podcast_desc_size',
            field=models.CharField(blank=True, default='1.05rem', max_length=20, verbose_name='Page Podcast — Taille description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_podcast_font',
            field=models.CharField(blank=True, choices=[('inherit', 'Par défaut'), ("'Poppins', sans-serif", 'Poppins'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Playfair Display', serif", 'Playfair Display'), ("'Roboto', sans-serif", 'Roboto'), ("'Raleway', sans-serif", 'Raleway'), ("'Oswald', sans-serif", 'Oswald'), ("'Lora', serif", 'Lora')], default='inherit', max_length=100, verbose_name='Page Podcast — Police'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_podcast_titre_bold',
            field=models.BooleanField(default=True, verbose_name='Page Podcast — Titre gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_podcast_titre_italic',
            field=models.BooleanField(default=False, verbose_name='Page Podcast — Titre italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_podcast_titre_size',
            field=models.CharField(blank=True, default='2.4rem', max_length=20, verbose_name='Page Podcast — Taille titre'),
        ),
    ]
