# Generated by Django 4.2.28 on 2026-04-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0064_siteconfiguration_page_about_desc_bold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_image',
            field=models.ImageField(blank=True, null=True, upload_to='mots/', verbose_name='Photo Madame la Ministre'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_nom',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom Madame la Ministre'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_texte',
            field=models.TextField(blank=True, default='', verbose_name='Texte du mot de Madame la Ministre'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_titre',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Titre/Fonction Madame la Ministre'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_image',
            field=models.ImageField(blank=True, null=True, upload_to='mots/', verbose_name='Photo Professeur Baniré'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_nom',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom Professeur Baniré'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_texte',
            field=models.TextField(blank=True, default='', verbose_name='Texte du mot du Professeur Baniré'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_titre',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Titre/Fonction Professeur Baniré'),
        ),
    ]
