# Generated by Django 4.2.28 on 2026-04-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0065_siteconfiguration_mot_ministre_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_texte_bold',
            field=models.BooleanField(default=False, verbose_name='Mot Ministre — Texte en gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_texte_color',
            field=models.CharField(blank=True, default='#334155', max_length=20, verbose_name='Mot Ministre — Couleur texte'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_texte_font',
            field=models.CharField(blank=True, default='inherit', max_length=100, verbose_name='Mot Ministre — Police'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_texte_italic',
            field=models.BooleanField(default=False, verbose_name='Mot Ministre — Texte en italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_texte_size',
            field=models.CharField(blank=True, default='0.95rem', max_length=20, verbose_name='Mot Ministre — Taille texte'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_texte_bold',
            field=models.BooleanField(default=False, verbose_name='Mot Professeur — Texte en gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_texte_color',
            field=models.CharField(blank=True, default='#334155', max_length=20, verbose_name='Mot Professeur — Couleur texte'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_texte_font',
            field=models.CharField(blank=True, default='inherit', max_length=100, verbose_name='Mot Professeur — Police'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_texte_italic',
            field=models.BooleanField(default=False, verbose_name='Mot Professeur — Texte en italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_texte_size',
            field=models.CharField(blank=True, default='0.95rem', max_length=20, verbose_name='Mot Professeur — Taille texte'),
        ),
    ]
