# Generated by Django 4.2.28 on 2026-04-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0066_siteconfiguration_mot_ministre_texte_bold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_nom_bold',
            field=models.BooleanField(default=True, verbose_name='Mot Ministre — Nom en gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_nom_color',
            field=models.CharField(blank=True, default='#003366', max_length=20, verbose_name='Mot Ministre — Couleur nom'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_nom_font',
            field=models.CharField(blank=True, default='inherit', max_length=100, verbose_name='Mot Ministre — Police nom'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_nom_italic',
            field=models.BooleanField(default=False, verbose_name='Mot Ministre — Nom en italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_nom_size',
            field=models.CharField(blank=True, default='1rem', max_length=20, verbose_name='Mot Ministre — Taille nom'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_titre_bold',
            field=models.BooleanField(default=False, verbose_name='Mot Ministre — Titre en gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_titre_color',
            field=models.CharField(blank=True, default='#8896a7', max_length=20, verbose_name='Mot Ministre — Couleur titre'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_titre_font',
            field=models.CharField(blank=True, default='inherit', max_length=100, verbose_name='Mot Ministre — Police titre'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_titre_italic',
            field=models.BooleanField(default=False, verbose_name='Mot Ministre — Titre en italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_ministre_titre_size',
            field=models.CharField(blank=True, default='0.85rem', max_length=20, verbose_name='Mot Ministre — Taille titre/fonction'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_nom_bold',
            field=models.BooleanField(default=True, verbose_name='Mot Professeur — Nom en gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_nom_color',
            field=models.CharField(blank=True, default='#003366', max_length=20, verbose_name='Mot Professeur — Couleur nom'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_nom_font',
            field=models.CharField(blank=True, default='inherit', max_length=100, verbose_name='Mot Professeur — Police nom'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_nom_italic',
            field=models.BooleanField(default=False, verbose_name='Mot Professeur — Nom en italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_nom_size',
            field=models.CharField(blank=True, default='1rem', max_length=20, verbose_name='Mot Professeur — Taille nom'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_titre_bold',
            field=models.BooleanField(default=False, verbose_name='Mot Professeur — Titre en gras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_titre_color',
            field=models.CharField(blank=True, default='#8896a7', max_length=20, verbose_name='Mot Professeur — Couleur titre'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_titre_font',
            field=models.CharField(blank=True, default='inherit', max_length=100, verbose_name='Mot Professeur — Police titre'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_titre_italic',
            field=models.BooleanField(default=False, verbose_name='Mot Professeur — Titre en italique'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mot_professeur_titre_size',
            field=models.CharField(blank=True, default='0.85rem', max_length=20, verbose_name='Mot Professeur — Taille titre/fonction'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='mot_ministre_texte_font',
            field=models.CharField(blank=True, default='inherit', max_length=100, verbose_name='Mot Ministre — Police texte'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='mot_professeur_texte_font',
            field=models.CharField(blank=True, default='inherit', max_length=100, verbose_name='Mot Professeur — Police texte'),
        ),
    ]
