# Generated by Django 4.2.28 on 2026-04-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0067_siteconfiguration_mot_ministre_nom_bold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_about_hero_video',
            field=models.FileField(blank=True, null=True, upload_to='pages_hero_video/', verbose_name='Page À propos — Vidéo hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_ateliers_hero_video',
            field=models.FileField(blank=True, null=True, upload_to='pages_hero_video/', verbose_name='Page Ateliers — Vidéo hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_evenements_hero_video',
            field=models.FileField(blank=True, null=True, upload_to='pages_hero_video/', verbose_name='Page Événements — Vidéo hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_livrable_hero_video',
            field=models.FileField(blank=True, null=True, upload_to='pages_hero_video/', verbose_name='Page Livrable — Vidéo hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_podcast_hero_video',
            field=models.FileField(blank=True, null=True, upload_to='pages_hero_video/', verbose_name='Page Podcast — Vidéo hero'),
        ),
    ]
