# Generated by Django 5.2.14 on 2026-06-14 22:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0068_add_hero_video_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom de la rubrique')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('couleur', models.CharField(blank=True, default='#003366', max_length=20, verbose_name='Couleur (badge)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Rubrique',
                'verbose_name_plural': 'Rubriques',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='Slug (URL)')),
                ('chapo', models.TextField(blank=True, default='', help_text='Court résumé affiché en introduction', verbose_name='Sous-titre / Chapô')),
                ('corps', models.TextField(blank=True, default='', help_text='Contenu riche (HTML)', verbose_name="Corps de l'article")),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Image à la une (upload)')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Image à la une (URL fallback)')),
                ('image_legende', models.CharField(blank=True, default='', max_length=255, verbose_name="Légende de l'image")),
                ('tags', models.CharField(blank=True, default='', max_length=300, verbose_name='Étiquettes (séparées par des virgules)')),
                ('auteur_nom', models.CharField(blank=True, default='', help_text='Laisser vide pour utiliser le compte', max_length=150, verbose_name="Nom de l'auteur (affiché)")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('programme', 'Programmé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('visibilite', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé (admin uniquement)'), ('membres', 'Membres connectés')], default='public', max_length=20, verbose_name='Visibilité')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, help_text='Pour un article programmé, date future de mise en ligne', verbose_name='Date de publication')),
                ('epingle', models.BooleanField(default=False, verbose_name='Mettre en avant / Épingler')),
                ('autoriser_commentaires', models.BooleanField(default=True, verbose_name='Autoriser les commentaires')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Meta titre (SEO)')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='Meta description (SEO)')),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteur (compte)')),
                ('rubrique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='inscriptions.rubrique', verbose_name='Rubrique')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication', '-created_at'],
            },
        ),
    ]
