# Generated by Django 5.2.14 on 2026-06-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0069_rubrique_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='afficher_accueil',
            field=models.BooleanField(default=False, verbose_name="Afficher sur l'accueil"),
        ),
        migrations.AddField(
            model_name='article',
            name='afficher_apropos',
            field=models.BooleanField(default=False, verbose_name='Afficher sur la page À propos'),
        ),
        migrations.AddField(
            model_name='article',
            name='afficher_ateliers',
            field=models.BooleanField(default=False, verbose_name='Afficher sur la page Ateliers'),
        ),
        migrations.AddField(
            model_name='article',
            name='afficher_evenements',
            field=models.BooleanField(default=False, verbose_name='Afficher sur la page Événements'),
        ),
        migrations.AddField(
            model_name='article',
            name='afficher_livrables',
            field=models.BooleanField(default=False, verbose_name='Afficher sur la page Livrable'),
        ),
        migrations.AddField(
            model_name='article',
            name='afficher_podcast',
            field=models.BooleanField(default=False, verbose_name='Afficher sur la page Podcast'),
        ),
    ]
