# Generated by Django 4.2.9 on 2026-08-09 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0070_article_afficher_accueil_article_afficher_apropos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Identifiant unique')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénoms')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('telephone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone')),
                ('organisation', models.CharField(blank=True, default='', max_length=200, verbose_name='Organisation / Institution')),
                ('categorie', models.CharField(choices=[('grand_public', 'Grand public'), ('speaker', 'Speaker'), ('sponsor', 'Sponsor'), ('presse', 'Presse'), ('vip', 'VIP'), ('staff', 'Staff'), ('organisateur', 'Organisateur')], default='grand_public', max_length=20, verbose_name='Catégorie')),
                ('badge_pdf', models.FileField(blank=True, null=True, upload_to='badges/', verbose_name='Badge PDF généré')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('valide', models.BooleanField(default=False, verbose_name='Inscription validée')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
            ],
            options={
                'verbose_name': 'Inscription Conférence',
                'verbose_name_plural': 'Inscriptions Conférence',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
