# Generated by Django 4.2.9 on 2026-08-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0071_inscriptionconference'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('grand_public', 'Grand public'), ('speaker', 'Speaker'), ('sponsor', 'Sponsor'), ('presse', 'Presse'), ('vip', 'VIP'), ('staff', 'Staff'), ('organisateur', 'Organisateur')], max_length=20, unique=True, verbose_name='Catégorie')),
                ('template_image', models.ImageField(upload_to='badges_templates/', verbose_name='Image template (PNG, 591x1004 px)')),
                ('nom_x', models.IntegerField(default=200, verbose_name='Nom — position X')),
                ('nom_y', models.IntegerField(default=555, verbose_name='Nom — position Y')),
                ('nom_font_size', models.IntegerField(default=28, verbose_name='Nom — taille police')),
                ('nom_color', models.CharField(default='#FFFFFF', max_length=20, verbose_name='Nom — couleur')),
                ('prenom_x', models.IntegerField(default=200, verbose_name='Prénoms — position X')),
                ('prenom_y', models.IntegerField(default=655, verbose_name='Prénoms — position Y')),
                ('prenom_font_size', models.IntegerField(default=28, verbose_name='Prénoms — taille police')),
                ('prenom_color', models.CharField(default='#FFFFFF', max_length=20, verbose_name='Prénoms — couleur')),
                ('qr_x1', models.IntegerField(default=231, verbose_name='QR code — X1')),
                ('qr_y1', models.IntegerField(default=791, verbose_name='QR code — Y1')),
                ('qr_x2', models.IntegerField(default=394, verbose_name='QR code — X2')),
                ('qr_y2', models.IntegerField(default=954, verbose_name='QR code — Y2')),
                ('date_upload', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de badge',
                'verbose_name_plural': 'Templates de badges',
                'ordering': ['categorie'],
            },
        ),
    ]
