# Generated by Django 5.1.15 on 2026-08-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0072_badgetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='source_connaissance',
            field=models.CharField(blank=True, choices=[('web_reseaux', 'Site web ou réseaux sociaux'), ('bouche_a_oreille', 'Par un ami, un collègue ou une connaissance'), ('lettre_invitation', "Par une lettre d'invitation officielle"), ('autre', 'Autre')], default='', max_length=50, verbose_name='Comment avez-vous connu DounIA² ?'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='source_connaissance_courrier_numero',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name="N° du courrier d'invitation"),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='disponibilite',
            field=models.CharField(blank=True, choices=[('semaine', 'En semaine (journée)'), ('soir', 'En soirée'), ('weekend', 'Le week-end'), ('flexible', 'Flexible')], default='', max_length=50, verbose_name='Disponibilité'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='format_preference',
            field=models.CharField(blank=True, choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('hybride', 'Hybride (présentiel + distanciel)')], default='', max_length=50, verbose_name='Format préféré'),
        ),
    ]
